version: 2.1
commands:
  docker_login:
    parameters:
      gcloud_auth_var_name:
        type: string
        default: ""
    steps:
      - run:
          name: extract auth json to file and login
          command: |
            GOOGLE_APPLICATION_CREDENTIALS="/tmp/gac-$(date +%s).json"
            echo "${<<parameters.gcloud_auth_var_name>>}" | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
            cat $GOOGLE_APPLICATION_CREDENTIALS | docker login -u _json_key --password-stdin https://gcr.io
            rm ${GOOGLE_APPLICATION_CREDENTIALS}
  update_version_in_runai_operator:
    steps:
      - run:
          name: Install tools
          command: cd ~ && GO111MODULE=on go get github.com/mikefarah/yq/v4

      - run:
          name: Git Commands
          command: |
            export TAG=${CIRCLE_TAG/v/''}
            echo "Updating mig-parted new version number $TAG in runai-operator..."
            cd ~
            git config --global -l
            git config --global user.name "circleci-runai"
            git config --global user.email "circleci@run.ai"
            git clone https://github.com/run-ai/runai-operator.git
            cd runai-operator/subcharts/mig-parted
            echo $TAG
            yq e -i '.image.tag = strenv(TAG)' values.yaml
            cat values.yaml
            git add values.yaml
            git commit -m "updated mig-parted production version to $TAG [skip ci]"
            git push
jobs:      
  deploy-staging:
    working_directory: ~/runai
    docker:
    - image: circleci/golang:1.15
    steps:
    - checkout
    - setup_remote_docker
    - docker_login:
        gcloud_auth_var_name: STAGING_GCLOUD_SERVICE_JSON_CONTENT
    - run:
        name: Build And Push to google cloud staging registry with latest tag
        command: cd deployments/gpu-operator && make
        environment:
          ENVIRONMENT: staging
          VERSION: latest
    - run:
        name: Push to google cloud staging registry with 'latest' tag
        command: cd deployments/gpu-operator && make push-to-tag
        environment:
          ENVIRONMENT: staging
          OLD_TAG: latest
          NEW_TAG: <<pipeline.git.revision>>

  deploy-production:
    working_directory: ~/runai
    docker:
    - image: circleci/golang:1.15
    steps:
    - checkout
    - setup_remote_docker
    - docker_login:
        gcloud_auth_var_name: PRODUCTION_GCLOUD_SERVICE_JSON_CONTENT
    - run:
        name: Build And Push to google cloud production registry
        command: cd deployments/gpu-operator && make
        environment:
          ENVIRONMENT: prod
          VERSION: <<pipeline.git.tag>>
    - update_version_in_runai_operator

workflows:
  version: 2  
  deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only:
                - "gal/RUN-2662-add-tag-and-trigger-operator-update-version"
      - deploy-production:
          filters:
                tags:
                  only: /^v.*/
                branches:
                  ignore: /.*/

